# Generated by Django 3.1 on 2020-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.CharField(max_length=200)),
                ('Pass', models.CharField(max_length=12)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('Use_Level', models.IntegerField(default=0)),
            ],
        ),
    ]
