# Generated by Django 3.1 on 2020-08-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mon', models.CharField(max_length=200)),
                ('Tue', models.CharField(max_length=200)),
                ('Wed', models.CharField(max_length=200)),
                ('Tur', models.CharField(max_length=200)),
                ('Fri', models.CharField(max_length=200)),
                ('Inputdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
