# Generated by Django 3.1 on 2020-08-19 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HanseiApp', '0002_auto_20200819_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='User',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
