# Generated by Django 3.1 on 2020-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0005_auto_20200819_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='Fri',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='Mon',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='Tue',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='Tur',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='Wed',
        ),
        migrations.AddField(
            model_name='scheduleinfo',
            name='AvailableTime',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleinfo',
            name='AvailableworkHourDay',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleinfo',
            name='AvailableworkHourWeek',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleinfo',
            name='DayOff',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheduleinfo',
            name='Fixedclasses',
            field=models.TextField(null=True),
        ),
    ]
