# Generated by Django 3.1 on 2020-08-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0006_auto_20200820_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleinfo',
            old_name='AvailableTime',
            new_name='TimetableCellInfo',
        ),
    ]
