# Generated by Django 3.1 on 2020-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0007_auto_20200822_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassInfo', models.TextField(null=True)),
            ],
        ),
    ]
