# Generated by Django 3.1 on 2020-08-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0008_classesinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleinfo',
            old_name='Fixedclasses',
            new_name='Memo',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='AvailableworkHourDay',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='AvailableworkHourWeek',
        ),
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='DayOff',
        ),
    ]
