# Generated by Django 3.1 on 2020-08-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0009_auto_20200825_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
