# Generated by Django 3.1 on 2020-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanseiApp', '0010_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='ImpertedExcel',
            field=models.TextField(null=True),
        ),
    ]
